#ifndef __STM8S_IT_H
  #define __STM8S_IT_H
  #include "stm8s.h"
  INTERRUPT_HANDLER_TRAP(TRAP_IRQHandler);                 // TRAP
  INTERRUPT_HANDLER(TLI_IRQHandler, 0);                    // TLI
  INTERRUPT_HANDLER(AWU_IRQHandler, 1);                    // AWU
  INTERRUPT_HANDLER(CLK_IRQHandler, 2);                    // CLOCK
  INTERRUPT_HANDLER(EXTI_PORTA_IRQHandler, 3);             // EXTI PORTA
  INTERRUPT_HANDLER(EXTI_PORTB_IRQHandler, 4);             // EXTI PORTB
  INTERRUPT_HANDLER(EXTI_PORTC_IRQHandler, 5);             // EXTI PORTC
  INTERRUPT_HANDLER(EXTI_PORTD_IRQHandler, 6);             // EXTI PORTD
  INTERRUPT_HANDLER(EXTI_PORTE_IRQHandler, 7);             // EXTI PORTE
  INTERRUPT_HANDLER(EXTI_PORTF_IRQHandler, 8);             // EXTI PORTF
  INTERRUPT_HANDLER(TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11);  // TIM1 UPD/OVF/TRG/BRK
  INTERRUPT_HANDLER(TIM1_CAP_COM_IRQHandler, 12);          // TIM1 CAP/COM
  INTERRUPT_HANDLER(TIM2_UPD_OVF_BRK_IRQHandler, 13);      // TIM2 UPD/OVF/BRK
  INTERRUPT_HANDLER(TIM2_CAP_COM_IRQHandler, 14);          // TIM2 CAP/COM
  INTERRUPT_HANDLER(TIM3_UPD_OVF_BRK_IRQHandler, 15);      // TIM3 UPD/OVF/BRK
  INTERRUPT_HANDLER(TIM3_CAP_COM_IRQHandler, 16);          // TIM3 CAP/COM
  INTERRUPT_HANDLER(UART1_TX_IRQHandler, 17);              // UART1 TX
  INTERRUPT_HANDLER(UART1_RX_IRQHandler, 18);              // UART1 RX
#endif /* __STM8S_IT_H */
